# Generated by Django 3.1.7 on 2022-04-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0005_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
