# Generated by Django 3.1.7 on 2022-04-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0020_remove_comment_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
